# 네임스페이스 생성
apiVersion: v1
kind: Namespace
metadata:
  name: edu-user
---
apiVersion: v1
kind: Namespace
metadata:
  name: edu-goods
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-edu-user-deployment
spec:
  selector:
    matchLabels:
      app: k8s-edu-user-app
  replicas: 2
  template:
    metadata:
      labels:
        app: k8s-edu-user-app
        version: blue
    spec:
      containers:
        - name: k8s-edu-user-app
          image: sjin2pio/k8s-edu:v0.0.2      # dockerhub image repository : repo/image명:Tag
          imagePullPolicy: IfNotPresent        # k8s 클러스터에 다운로드 된 이미지 없으면 다운 or Always
          ports:
            - name: http
              containerPort: 8080              # demo.jar 실행 포트
              protocol: TCP
          resources:                           # pod 사용 리소스 설정 블록
            requests:                          # 생성시 필요한 최소 리소스
              cpu: "1"
              memory: "2Gi"
            limits:                            # pod가 사용 가능한 최대 리소스
              cpu: "1"
              memory: "2Gi"
          env:                                 # pod 내 환경 변수 설정
            - name: SPRING_PROFILES_ACTIVE     # spring profile 설정
              value: prod                      # 상용(prod) 환경
      imagePullSecrets:                        # dockerhub 이미지 pull 위한 secret
        - name: k8s-edu-dockerhub-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-edu-goods-deployment
spec:
  selector:
    matchLabels:
      app: k8s-edu-goods-app
  replicas: 2
  template:
    metadata:
      labels:
        app: k8s-edu-goods-app
        version: blue
    spec:
      containers:
        - name: k8s-edu-goods-app
          image: sjin2pio/k8s-edu:v0.0.2      # dockerhub image repository : repo/image명:Tag
          imagePullPolicy: IfNotPresent        # k8s 클러스터에 다운로드 된 이미지 없으면 다운 or Always
          ports:
            - name: http
              containerPort: 8080              # demo.jar 실행 포트
              protocol: TCP
          resources:                           # pod 사용 리소스 설정 블록
            requests:                          # 생성시 필요한 최소 리소스
              cpu: "1"
              memory: "2Gi"
            limits:                            # pod가 사용 가능한 최대 리소스
              cpu: "1"
              memory: "2Gi"
          env:                                 # pod 내 환경 변수 설정
            - name: SPRING_PROFILES_ACTIVE     # spring profile 설정
              value: prod                      # 상용(prod) 환경
      imagePullSecrets:                        # dockerhub 이미지 pull 위한 secret
        - name: k8s-edu-dockerhub-secret
---
# Horizontal Pod Autoscaler (HPA) 설정
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: edu-user-hpa
  namespace: edu-user
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: k8s-edu-user-deployment
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 30
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: edu-goods-hpa
  namespace: edu-goods
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: k8s-edu-goods-deployment
  minReplicas: 2
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 30